project:
  type: website

date: 2024-07-20
lang: de

website:
  title: "_TEMPLATE"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "The Index file you are seing right now"
        href: index.qmd
      - text: "The Readme file for good measures"
        href: Readme.md

execute:
  freeze: true
  cache: true


bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly