project:
  type: website

website:
  title: "Über das wissenschaftliche Schreiben"
  sidebar:
    contents:
      - README.md

execute:
  freeze: true
  cache: true


bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    	

render:
  dpi: 1