project:
  type: website

date: 2024-07-20
lang: de

website:
  title: "_TEMPLATE"
  sidebar:
    style: "docked"
    search: true
    contents:
      - README.md
      - index.qmd

execute:
  freeze: true
  cache: true


bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly